// THIS FILE WAS AUTOMATICALLY GENERATED.
// Source: python-sc2 sc2/dicts/unit_abilities.py

use crate::ids::{AbilityId, UnitTypeId};
use std::collections::{HashMap, HashSet};
use lazy_static::lazy_static;

lazy_static! {
	pub static ref UnitAbilities: HashMap<UnitTypeId, HashSet<AbilityId>> = {
		let mut m = HashMap::new();
		m.insert(
			UnitTypeId::Colossus,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::TechLab,
			HashSet::from([
				AbilityId::BarracksTechLabResearchStimpack,
				AbilityId::ResearchCombatShield,
				AbilityId::ResearchConcussiveShells,
				AbilityId::ResearchInfernalPreigniter,
				AbilityId::ResearchDrillingClaws,
				AbilityId::ResearchBansheeCloakingField,
				AbilityId::ResearchRavenCorvidReactor,
			]),
		);
		m.insert(
			UnitTypeId::InfestorTerran,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BurrowDownInfestorTerran,
			]),
		);
		m.insert(
			UnitTypeId::BanelingCocoon,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
			]),
		);
		m.insert(
			UnitTypeId::Baneling,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::ExplodeExplode,
				AbilityId::BurrowDownBaneling,
				AbilityId::BehaviorBuildingAttackOn,
			]),
		);
		m.insert(
			UnitTypeId::Mothership,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectMassRecallStrategicRecall,
				AbilityId::EffectTimeWarp,
				AbilityId::LoadOutSprayLoadOutSpray12,
			]),
		);
		m.insert(
			UnitTypeId::Changeling,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::ChangelingZealot,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::ChangelingMarineShield,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::ChangelingMarine,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::ChangelingZerglingWings,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::ChangelingZergling,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::CommandCenter,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyCommandCenter,
				AbilityId::LoadAllCommandCenter,
				AbilityId::LiftCommandCenter,
				AbilityId::CommandCenterTrainSCV,
				AbilityId::UpgradeToPlanetaryFortressPlanetaryFortress,
				AbilityId::UpgradeToOrbitalOrbitalCommand,
			]),
		);
		m.insert(
			UnitTypeId::SupplyDepot,
			HashSet::from([
				AbilityId::MorphSupplyDepotLower,
			]),
		);
		m.insert(
			UnitTypeId::Barracks,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::BuildTechLabBarracks,
				AbilityId::BuildReactorBarracks,
				AbilityId::LiftBarracks,
				AbilityId::BarracksTrainMarine,
				AbilityId::BarracksTrainReaper,
				AbilityId::BarracksTrainGhost,
				AbilityId::BarracksTrainMarauder,
			]),
		);
		m.insert(
			UnitTypeId::EngineeringBay,
			HashSet::from([
				AbilityId::ResearchHiSecAutoTracking,
				AbilityId::ResearchTerranStructureArmorUpgrade,
				AbilityId::EngineeringBayResearchTerranInfantryWeaponsLevel1,
				AbilityId::EngineeringBayResearchTerranInfantryWeaponsLevel2,
				AbilityId::EngineeringBayResearchTerranInfantryWeaponsLevel3,
				AbilityId::EngineeringBayResearchTerranInfantryArmorLevel1,
				AbilityId::EngineeringBayResearchTerranInfantryArmorLevel2,
				AbilityId::EngineeringBayResearchTerranInfantryArmorLevel3,
			]),
		);
		m.insert(
			UnitTypeId::MissileTurret,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Bunker,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::LoadBunker,
				// Ability SALVAGEEFFECT_SALVAGE(4128) not in Rust enums,
			]),
		);
	// SENSORTOWER(25) abilities missing
		m.insert(
			UnitTypeId::GhostAcademy,
			HashSet::from([
				AbilityId::BuildNuke,
				AbilityId::ResearchPersonalCloaking,
			]),
		);
		m.insert(
			UnitTypeId::Factory,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::BuildTechLabFactory,
				AbilityId::BuildReactorFactory,
				AbilityId::LiftFactory,
				AbilityId::FactoryTrainSiegeTank,
				AbilityId::FactoryTrainThor,
				AbilityId::FactoryTrainHellion,
				AbilityId::TrainHellbat,
				AbilityId::TrainCyclone,
				AbilityId::FactoryTrainWidowMine,
			]),
		);
		m.insert(
			UnitTypeId::Starport,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::BuildTechLabStarport,
				AbilityId::BuildReactorStarport,
				AbilityId::LiftStarport,
				AbilityId::StarportTrainMedivac,
				AbilityId::StarportTrainBanshee,
				AbilityId::StarportTrainRaven,
				AbilityId::StarportTrainBattlecruiser,
				AbilityId::StarportTrainVikingFighter,
				AbilityId::StarportTrainLiberator,
			]),
		);
		m.insert(
			UnitTypeId::Armory,
			HashSet::from([
				AbilityId::ArmoryResearchTerranVehicleWeaponsLevel1,
				AbilityId::ArmoryResearchTerranVehicleWeaponsLevel2,
				AbilityId::ArmoryResearchTerranVehicleWeaponsLevel3,
				AbilityId::ArmoryResearchTerranShipWeaponsLevel1,
				AbilityId::ArmoryResearchTerranShipWeaponsLevel2,
				AbilityId::ArmoryResearchTerranShipWeaponsLevel3,
				AbilityId::ArmoryResearchTerranVehicleAndShipPlatingLevel1,
				AbilityId::ArmoryResearchTerranVehicleAndShipPlatingLevel2,
				AbilityId::ArmoryResearchTerranVehicleAndShipPlatingLevel3,
			]),
		);
		m.insert(
			UnitTypeId::FusionCore,
			HashSet::from([
				AbilityId::ResearchBattlecruiserWeaponRefit,
				AbilityId::FusionCoreResearchBallisticRange,
				AbilityId::FusionCoreResearchMedivacEnergyUpgrade,
			]),
		);
		m.insert(
			UnitTypeId::AutoTurret,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::SiegeTankSieged,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::UnsiegeUnsiege,
			]),
		);
		m.insert(
			UnitTypeId::SiegeTank,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::SiegeModeSiegeMode,
			]),
		);
		m.insert(
			UnitTypeId::VikingAssault,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphVikingFighterMode,
			]),
		);
		m.insert(
			UnitTypeId::VikingFighter,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphVikingAssaultMode,
			]),
		);
		m.insert(
			UnitTypeId::CommandCenterFlying,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::LoadAllCommandCenter,
				AbilityId::LandCommandCenter,
			]),
		);
		m.insert(
			UnitTypeId::BarracksTechLab,
			HashSet::from([
				AbilityId::BarracksTechLabResearchStimpack,
				AbilityId::ResearchCombatShield,
				AbilityId::ResearchConcussiveShells,
			]),
		);
		m.insert(
			UnitTypeId::FactoryTechLab,
			HashSet::from([
				AbilityId::ResearchInfernalPreigniter,
				AbilityId::ResearchDrillingClaws,
				AbilityId::ResearchSmartServos,
				AbilityId::ResearchCycloneLockOnDamage,
			]),
		);
		m.insert(
			UnitTypeId::StarportTechLab,
			HashSet::from([
				AbilityId::ResearchBansheeCloakingField,
				AbilityId::ResearchBansheeHyperflightRotors,
				AbilityId::StarportTechLabResearchRavenInterferenceMatrix,
			]),
		);
		m.insert(
			UnitTypeId::FactoryFlying,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::BuildTechLabFactory,
				AbilityId::BuildReactorFactory,
				AbilityId::LandFactory,
			]),
		);
		m.insert(
			UnitTypeId::StarportFlying,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::BuildTechLabStarport,
				AbilityId::BuildReactorStarport,
				AbilityId::LandStarport,
			]),
		);
		m.insert(
			UnitTypeId::SCV,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectSprayTerran,
				AbilityId::HarvestGatherSCV,
				AbilityId::EffectRepairSCV,
				AbilityId::TerranBuildCommandCenter,
				AbilityId::TerranBuildSupplyDepot,
				AbilityId::TerranBuildRefinery,
				AbilityId::TerranBuildBarracks,
				AbilityId::TerranBuildEngineeringBay,
				AbilityId::TerranBuildMissileTurret,
				AbilityId::TerranBuildBunker,
				AbilityId::TerranBuildSensorTower,
				AbilityId::TerranBuildGhostAcademy,
				AbilityId::TerranBuildFactory,
				AbilityId::TerranBuildStarport,
				AbilityId::TerranBuildArmory,
				AbilityId::TerranBuildFusionCore,
			]),
		);
		m.insert(
			UnitTypeId::BarracksFlying,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::BuildTechLabBarracks,
				AbilityId::BuildReactorBarracks,
				AbilityId::LandBarracks,
			]),
		);
		m.insert(
			UnitTypeId::SupplyDepotLowered,
			HashSet::from([
				AbilityId::MorphSupplyDepotRaise,
			]),
		);
		m.insert(
			UnitTypeId::Marine,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectStimMarine,
			]),
		);
		m.insert(
			UnitTypeId::Reaper,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::KD8ChargeKD8Charge,
			]),
		);
		m.insert(
			UnitTypeId::Ghost,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BehaviorHoldFireOnGhost,
				AbilityId::BehaviorCloakOnGhost,
				AbilityId::EMPEMP,
				AbilityId::EffectGhostSnipe,
			]),
		);
		m.insert(
			UnitTypeId::Marauder,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectStimMarauder,
			]),
		);
		m.insert(
			UnitTypeId::Thor,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphThorHighImpactMode,
			]),
		);
		m.insert(
			UnitTypeId::Hellion,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphHellbat,
			]),
		);
		m.insert(
			UnitTypeId::Medivac,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::MedivacHealHeal,
				AbilityId::LoadMedivac,
				AbilityId::EffectMedivacIgniteAfterburners,
			]),
		);
		m.insert(
			UnitTypeId::Banshee,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BehaviorCloakOnBanshee,
			]),
		);
		m.insert(
			UnitTypeId::Raven,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::BuildAutoTurretAutoTurret,
				AbilityId::EffectInterferenceMatrix,
				AbilityId::EffectAntiArmorMissile,
			]),
		);
		m.insert(
			UnitTypeId::Battlecruiser,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::YamatoYamatoGun,
				AbilityId::EffectTacticalJump,
				AbilityId::AttackBattlecruiser,
				AbilityId::MoveBattlecruiser,
				AbilityId::PatrolBattlecruiser,
				AbilityId::HoldPositionBattlecruiser,
				AbilityId::StopBattlecruiser,
			]),
		);
		m.insert(
			UnitTypeId::Nexus,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::NexusTrainMothershipMothership,
				AbilityId::RallyNexus,
				AbilityId::NexusTrainProbe,
				AbilityId::EffectChronoBoostEnergyCost,
				AbilityId::EffectMassRecallNexus,
				AbilityId::LoadOutSprayLoadOutSpray14,
			]),
		);
		m.insert(
			UnitTypeId::Gateway,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::GatewayTrainZealot,
				AbilityId::GatewayTrainStalker,
				AbilityId::GatewayTrainHighTemplar,
				AbilityId::GatewayTrainDarkTemplar,
				AbilityId::GatewayTrainSentry,
				AbilityId::TrainAdept,
				AbilityId::MorphWarpGate,
			]),
		);
		m.insert(
			UnitTypeId::Forge,
			HashSet::from([
				AbilityId::ForgeResearchProtossGroundWeaponsLevel1,
				AbilityId::ForgeResearchProtossGroundWeaponsLevel2,
				AbilityId::ForgeResearchProtossGroundWeaponsLevel3,
				AbilityId::ForgeResearchProtossGroundArmorLevel1,
				AbilityId::ForgeResearchProtossGroundArmorLevel2,
				AbilityId::ForgeResearchProtossGroundArmorLevel3,
				AbilityId::ForgeResearchProtossShieldsLevel1,
				AbilityId::ForgeResearchProtossShieldsLevel2,
				AbilityId::ForgeResearchProtossShieldsLevel3,
			]),
		);
		m.insert(
			UnitTypeId::FleetBeacon,
			HashSet::from([
				AbilityId::ResearchPhoenixAnionPulseCrystals,
				AbilityId::FleetBeaconResearchVoidRaySpeedUpgrade,
				AbilityId::FleetBeaconResearchTempestResearchGroundAttackUpgrade,
			]),
		);
		m.insert(
			UnitTypeId::TwilightCouncil,
			HashSet::from([
				AbilityId::ResearchCharge,
				AbilityId::ResearchBlink,
				AbilityId::ResearchAdeptResonatingGlaives,
			]),
		);
		m.insert(
			UnitTypeId::PhotonCannon,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Stargate,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::StargateTrainPhoenix,
				AbilityId::StargateTrainCarrier,
				AbilityId::StargateTrainVoidRay,
				AbilityId::StargateTrainOracle,
				AbilityId::StargateTrainTempest,
			]),
		);
		m.insert(
			UnitTypeId::TemplarArchive,
			HashSet::from([
				AbilityId::ResearchPsiStorm,
			]),
		);
		m.insert(
			UnitTypeId::DarkShrine,
			HashSet::from([
				AbilityId::ResearchShadowStrike,
			]),
		);
		m.insert(
			UnitTypeId::RoboticsBay,
			HashSet::from([
				AbilityId::ResearchGraviticBooster,
				AbilityId::ResearchGraviticDrive,
				AbilityId::ResearchExtendedThermalLance,
			]),
		);
		m.insert(
			UnitTypeId::RoboticsFacility,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::RoboticsFacilityTrainWarpPrism,
				AbilityId::RoboticsFacilityTrainObserver,
				AbilityId::RoboticsFacilityTrainColossus,
				AbilityId::RoboticsFacilityTrainImmortal,
				AbilityId::TrainDisruptor,
			]),
		);
		m.insert(
			UnitTypeId::CyberneticsCore,
			HashSet::from([
				AbilityId::CyberneticsCoreResearchProtossAirWeaponsLevel1,
				AbilityId::CyberneticsCoreResearchProtossAirWeaponsLevel2,
				AbilityId::CyberneticsCoreResearchProtossAirWeaponsLevel3,
				AbilityId::CyberneticsCoreResearchProtossAirArmorLevel1,
				AbilityId::CyberneticsCoreResearchProtossAirArmorLevel2,
				AbilityId::CyberneticsCoreResearchProtossAirArmorLevel3,
				AbilityId::ResearchWarpGate,
			]),
		);
		m.insert(
			UnitTypeId::Zealot,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectCharge,
			]),
		);
		m.insert(
			UnitTypeId::Stalker,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectBlinkStalker,
			]),
		);
		m.insert(
			UnitTypeId::HighTemplar,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::AttackAttack,
				AbilityId::FeedbackFeedback,
				AbilityId::PsiStormPsiStorm,
				AbilityId::MorphArchon,
			]),
		);
		m.insert(
			UnitTypeId::DarkTemplar,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphArchon,
				AbilityId::EffectShadowStride,
			]),
		);
		m.insert(
			UnitTypeId::Sentry,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::GuardianShieldGuardianShield,
				AbilityId::HallucinationArchon,
				AbilityId::HallucinationColossus,
				AbilityId::HallucinationHighTemplar,
				AbilityId::HallucinationImmortal,
				AbilityId::HallucinationPhoenix,
				AbilityId::HallucinationProbe,
				AbilityId::HallucinationStalker,
				AbilityId::HallucinationVoidRay,
				AbilityId::HallucinationWarpPrism,
				AbilityId::HallucinationZealot,
				AbilityId::ForceFieldForceField,
				AbilityId::HallucinationOracle,
				AbilityId::HallucinationDisruptor,
				AbilityId::HallucinationAdept,
			]),
		);
		m.insert(
			UnitTypeId::Phoenix,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::GravitonBeamGravitonBeam,
			]),
		);
		m.insert(
			UnitTypeId::Carrier,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::CancelHangarQueue5,
				AbilityId::BuildInterceptors,
			]),
		);
		m.insert(
			UnitTypeId::VoidRay,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectVoidRayPrismaticAlignment,
			]),
		);
		m.insert(
			UnitTypeId::WarpPrism,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::LoadWarpPrism,
				AbilityId::MorphWarpPrismPhasingMode,
			]),
		);
		m.insert(
			UnitTypeId::Observer,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::MorphSurveillanceMode,
			]),
		);
		m.insert(
			UnitTypeId::Immortal,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Probe,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectSprayProtoss,
				AbilityId::HarvestGatherProbe,
				AbilityId::ProtossBuildNexus,
				AbilityId::ProtossBuildPylon,
				AbilityId::ProtossBuildAssimilator,
				AbilityId::ProtossBuildGateway,
				AbilityId::ProtossBuildForge,
				AbilityId::ProtossBuildFleetBeacon,
				AbilityId::ProtossBuildTwilightCouncil,
				AbilityId::ProtossBuildPhotonCannon,
				AbilityId::ProtossBuildStargate,
				AbilityId::ProtossBuildTemplarArchive,
				AbilityId::ProtossBuildDarkShrine,
				AbilityId::ProtossBuildRoboticsBay,
				AbilityId::ProtossBuildRoboticsFacility,
				AbilityId::ProtossBuildCyberneticsCore,
				AbilityId::BuildShieldBattery,
			]),
		);
		m.insert(
			UnitTypeId::Interceptor,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Hatchery,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyHatcheryUnits,
				AbilityId::RallyHatcheryWorkers,
				AbilityId::UpgradeToLairLair,
				AbilityId::ResearchPneumatizedCarapace,
				AbilityId::ResearchBurrow,
				AbilityId::TrainQueenQueen,
			]),
		);
		m.insert(
			UnitTypeId::SpawningPool,
			HashSet::from([
				AbilityId::ResearchZerglingAdrenalGlands,
				AbilityId::ResearchZerglingMetabolicBoost,
			]),
		);
		m.insert(
			UnitTypeId::EvolutionChamber,
			HashSet::from([
				AbilityId::ResearchZergMeleeWeaponsLevel1,
				AbilityId::ResearchZergMeleeWeaponsLevel2,
				AbilityId::ResearchZergMeleeWeaponsLevel3,
				AbilityId::ResearchZergGroundArmorLevel1,
				AbilityId::ResearchZergGroundArmorLevel2,
				AbilityId::ResearchZergGroundArmorLevel3,
				AbilityId::ResearchZergMissileWeaponsLevel1,
				AbilityId::ResearchZergMissileWeaponsLevel2,
				AbilityId::ResearchZergMissileWeaponsLevel3,
			]),
		);
		m.insert(
			UnitTypeId::HydraliskDen,
			HashSet::from([
				AbilityId::ResearchGroovedSpines,
				AbilityId::ResearchMuscularAugments,
				// Ability HYDRALISKDENRESEARCH_RESEARCHFRENZY(1284) not in Rust enums,
			]),
		);
		m.insert(
			UnitTypeId::Spire,
			HashSet::from([
				AbilityId::UpgradeToGreaterSpireGreaterSpire,
				AbilityId::ResearchZergFlyerAttackLevel1,
				AbilityId::ResearchZergFlyerAttackLevel2,
				AbilityId::ResearchZergFlyerAttackLevel3,
				AbilityId::ResearchZergFlyerArmorLevel1,
				AbilityId::ResearchZergFlyerArmorLevel2,
				AbilityId::ResearchZergFlyerArmorLevel3,
			]),
		);
		m.insert(
			UnitTypeId::UltraliskCavern,
			HashSet::from([
				AbilityId::ResearchAnabolicSynthesis,
				AbilityId::ResearchChitinousPlating,
			]),
		);
		m.insert(
			UnitTypeId::InfestationPit,
			HashSet::from([
				AbilityId::ResearchNeuralParasite,
			]),
		);
		m.insert(
			UnitTypeId::NydusNetwork,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::RallyBuilding,
				AbilityId::LoadNydusNetwork,
				AbilityId::BuildNydusWorm,
			]),
		);
		m.insert(
			UnitTypeId::BanelingNest,
			HashSet::from([
				AbilityId::ResearchCentrifugalHooks,
			]),
		);
		m.insert(
			UnitTypeId::RoachWarren,
			HashSet::from([
				AbilityId::ResearchGlialRegeneration,
				AbilityId::ResearchTunnelingClaws,
			]),
		);
		m.insert(
			UnitTypeId::SpineCrawler,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::SpineCrawlerUprootSpineCrawlerUproot,
			]),
		);
		m.insert(
			UnitTypeId::SporeCrawler,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::SporeCrawlerUprootSporeCrawlerUproot,
			]),
		);
		m.insert(
			UnitTypeId::Lair,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyHatcheryUnits,
				AbilityId::RallyHatcheryWorkers,
				AbilityId::UpgradeToHiveHive,
				AbilityId::ResearchPneumatizedCarapace,
				AbilityId::ResearchBurrow,
				AbilityId::TrainQueenQueen,
			]),
		);
		m.insert(
			UnitTypeId::Hive,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyHatcheryUnits,
				AbilityId::RallyHatcheryWorkers,
				AbilityId::ResearchPneumatizedCarapace,
				AbilityId::ResearchBurrow,
				AbilityId::TrainQueenQueen,
			]),
		);
		m.insert(
			UnitTypeId::GreaterSpire,
			HashSet::from([
				AbilityId::ResearchZergFlyerAttackLevel1,
				AbilityId::ResearchZergFlyerAttackLevel2,
				AbilityId::ResearchZergFlyerAttackLevel3,
				AbilityId::ResearchZergFlyerArmorLevel1,
				AbilityId::ResearchZergFlyerArmorLevel2,
				AbilityId::ResearchZergFlyerArmorLevel3,
			]),
		);
		m.insert(
			UnitTypeId::Egg,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
			]),
		);
		m.insert(
			UnitTypeId::Drone,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectSprayZerg,
				AbilityId::ZergBuildHatchery,
				AbilityId::ZergBuildExtractor,
				AbilityId::ZergBuildSpawningPool,
				AbilityId::ZergBuildEvolutionChamber,
				AbilityId::ZergBuildHydraliskDen,
				AbilityId::ZergBuildSpire,
				AbilityId::ZergBuildUltraliskCavern,
				AbilityId::ZergBuildInfestationPit,
				AbilityId::ZergBuildNydusNetwork,
				AbilityId::ZergBuildBanelingNest,
				AbilityId::BuildLurkerDen,
				AbilityId::ZergBuildRoachWarren,
				AbilityId::ZergBuildSpineCrawler,
				AbilityId::ZergBuildSporeCrawler,
				AbilityId::HarvestGatherDrone,
				AbilityId::BurrowDownDrone,
			]),
		);
		m.insert(
			UnitTypeId::Zergling,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BurrowDownZergling,
				AbilityId::LoadOutSprayLoadOutSpray9,
			]),
		);
		m.insert(
			UnitTypeId::Overlord,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::MorphOverseer,
				AbilityId::BehaviorGenerateCreepOn,
				AbilityId::MorphOverlordTransport,
			]),
		);
		m.insert(
			UnitTypeId::Hydralisk,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BurrowDownHydralisk,
				AbilityId::MorphLurker,
				AbilityId::AmorphousArmorcloudAmorphousArmorcloud,
			]),
		);
		m.insert(
			UnitTypeId::Mutalisk,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Ultralisk,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BurrowDownUltralisk,
			]),
		);
		m.insert(
			UnitTypeId::Roach,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BurrowDownRoach,
				AbilityId::MorphToRavagerRavager,
			]),
		);
		m.insert(
			UnitTypeId::Infestor,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::FungalGrowthFungalGrowth,
				AbilityId::NeuralParasiteNeuralParasite,
				AbilityId::BurrowDownInfestorTerran,
				AbilityId::BurrowDownInfestor,
				AbilityId::ShieldBatteryRechargeEx5ShieldBatteryRecharge,
			]),
		);
		m.insert(
			UnitTypeId::Corruptor,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphToBroodLordBroodLord,
				AbilityId::CausticSprayCausticSpray,
			]),
		);
		m.insert(
			UnitTypeId::BroodLord,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::BanelingBurrowed,
			HashSet::from([
				AbilityId::ExplodeExplode,
				AbilityId::BurrowUpBaneling,
			]),
		);
		m.insert(
			UnitTypeId::DroneBurrowed,
			HashSet::from([
				AbilityId::BurrowUpDrone,
			]),
		);
		m.insert(
			UnitTypeId::HydraliskBurrowed,
			HashSet::from([
				AbilityId::BurrowUpHydralisk,
			]),
		);
		m.insert(
			UnitTypeId::RoachBurrowed,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::BurrowUpRoach,
			]),
		);
		m.insert(
			UnitTypeId::ZerglingBurrowed,
			HashSet::from([
				AbilityId::BurrowUpZergling,
			]),
		);
		m.insert(
			UnitTypeId::InfestorTerranBurrowed,
			HashSet::from([
				AbilityId::BurrowUpInfestorTerran,
			]),
		);
		m.insert(
			UnitTypeId::QueenBurrowed,
			HashSet::from([
				AbilityId::BurrowUpQueen,
			]),
		);
		m.insert(
			UnitTypeId::Queen,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectInjectLarva,
				AbilityId::BurrowDownQueen,
				AbilityId::TransfusionTransfusion,
				AbilityId::BuildCreepTumorQueen,
				AbilityId::BuildCreepTumor,
			]),
		);
		m.insert(
			UnitTypeId::InfestorBurrowed,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::NeuralParasiteNeuralParasite,
				AbilityId::BurrowUpInfestorTerran,
				AbilityId::BurrowUpInfestor,
			]),
		);
		m.insert(
			UnitTypeId::Overseer,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::SpawnChangelingSpawnChangeling,
				AbilityId::ContaminateContaminate,
				AbilityId::MorphOversightMode,
			]),
		);
		m.insert(
			UnitTypeId::PlanetaryFortress,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::RallyCommandCenter,
				AbilityId::LoadAllCommandCenter,
				AbilityId::CommandCenterTrainSCV,
			]),
		);
		m.insert(
			UnitTypeId::UltraliskBurrowed,
			HashSet::from([
				AbilityId::BurrowUpUltralisk,
			]),
		);
		m.insert(
			UnitTypeId::OrbitalCommand,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::CalldownMULECalldownMULE,
				AbilityId::RallyCommandCenter,
				AbilityId::SupplyDropSupplyDrop,
				AbilityId::ScannerSweepScan,
				AbilityId::CommandCenterTrainSCV,
				AbilityId::LiftOrbitalCommand,
			]),
		);
		m.insert(
			UnitTypeId::WarpGate,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::WarpGateTrainZealot,
				AbilityId::WarpGateTrainStalker,
				AbilityId::WarpGateTrainHighTemplar,
				AbilityId::WarpGateTrainDarkTemplar,
				AbilityId::WarpGateTrainSentry,
				AbilityId::TrainWarpAdept,
				AbilityId::MorphGateway,
			]),
		);
		m.insert(
			UnitTypeId::OrbitalCommandFlying,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::LandOrbitalCommand,
			]),
		);
		m.insert(
			UnitTypeId::WarpPrismPhasing,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::LoadWarpPrism,
				AbilityId::MorphWarpPrismTransportMode,
			]),
		);
		m.insert(
			UnitTypeId::CreepTumorBurrowed,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::BuildCreepTumorTumor,
				AbilityId::BuildCreepTumor,
			]),
		);
		m.insert(
			UnitTypeId::SpineCrawlerUprooted,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::SpineCrawlerRootSpineCrawlerRoot,
			]),
		);
		m.insert(
			UnitTypeId::SporeCrawlerUprooted,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::SporeCrawlerRootSporeCrawlerRoot,
			]),
		);
		m.insert(
			UnitTypeId::Archon,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::NydusCanal,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::RallyBuilding,
				AbilityId::LoadNydusWorm,
			]),
		);
		m.insert(
			UnitTypeId::GhostNova,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::BehaviorHoldFireOnGhost,
				AbilityId::BehaviorCloakOnGhost,
				AbilityId::EMPEMP,
				AbilityId::EffectGhostSnipe,
			]),
		);
		m.insert(
			UnitTypeId::Larva,
			HashSet::from([
				AbilityId::LarvaTrainDrone,
				AbilityId::LarvaTrainZergling,
				AbilityId::LarvaTrainOverlord,
				AbilityId::LarvaTrainHydralisk,
				AbilityId::LarvaTrainMutalisk,
				AbilityId::LarvaTrainUltralisk,
				AbilityId::LarvaTrainRoach,
				AbilityId::LarvaTrainInfestor,
				AbilityId::LarvaTrainCorruptor,
				AbilityId::LarvaTrainViper,
				AbilityId::TrainSwarmHost,
			]),
		);
		m.insert(
			UnitTypeId::MULE,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::EffectRepairMule,
				AbilityId::HarvestGatherMule,
			]),
		);
		m.insert(
			UnitTypeId::Broodling,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Adept,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::AdeptPhaseShiftAdeptPhaseShift,
			]),
		);
		m.insert(
			UnitTypeId::HellionTank,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphHellion,
			]),
		);
		m.insert(
			UnitTypeId::MothershipCore,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphMothership,
				AbilityId::EffectMassRecallMothershipCore,
				AbilityId::EffectPhotonOvercharge,
				AbilityId::EffectTimeWarp,
			]),
		);
		m.insert(
			UnitTypeId::LocustMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::NydusCanalAttacker,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::NydusCanalCreeper,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::DigesterCreepSprayDigesterCreepSpray,
			]),
		);
		m.insert(
			UnitTypeId::SwarmHostBurrowedMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::EffectSpawnLocusts,
			]),
		);
		m.insert(
			UnitTypeId::SwarmHostMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::BurrowDownSwarmHost,
				AbilityId::EffectSpawnLocusts,
			]),
		);
		m.insert(
			UnitTypeId::Oracle,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::AttackAttack,
				AbilityId::OracleRevelationOracleRevelation,
				AbilityId::BehaviorPulsarBeamOn,
				AbilityId::BuildStasisTrap,
			]),
		);
		m.insert(
			UnitTypeId::Tempest,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::WarHound,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::TornadoMissileTornadoMissile,
			]),
		);
		m.insert(
			UnitTypeId::WidowMine,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::BurrowDownWidowMine,
			]),
		);
		m.insert(
			UnitTypeId::Viper,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::BlindingCloudBlindingCloud,
				AbilityId::EffectAbduct,
				AbilityId::ViperConsumeStructureViperConsume,
				AbilityId::ParasiticBombParasiticBomb,
			]),
		);
		m.insert(
			UnitTypeId::WidowMineBurrowed,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::BurrowUpWidowMine,
				AbilityId::WidowMineAttackWidowMineAttack,
			]),
		);
		m.insert(
			UnitTypeId::LurkerMPEgg,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
			]),
		);
		m.insert(
			UnitTypeId::LurkerMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::AttackAttack,
				AbilityId::BurrowDownLurker,
			]),
		);
		m.insert(
			UnitTypeId::LurkerMPBurrowed,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::BurrowUpLurker,
				AbilityId::BehaviorHoldFireOnLurker,
			]),
		);
		m.insert(
			UnitTypeId::LurkerDenMP,
			HashSet::from([
				AbilityId::ResearchAdaptiveTalons,
				AbilityId::LurkerDenResearchLurkerRange,
			]),
		);
		m.insert(
			UnitTypeId::RavagerCocoon,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
			]),
		);
		m.insert(
			UnitTypeId::Ravager,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectCorrosiveBile,
				AbilityId::BurrowDownRavager,
			]),
		);
		m.insert(
			UnitTypeId::Liberator,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphLiberatorAGMode,
			]),
		);
		m.insert(
			UnitTypeId::RavagerBurrowed,
			HashSet::from([
				AbilityId::BurrowUpRavager,
			]),
		);
		m.insert(
			UnitTypeId::ThorAP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::MorphThorExplosiveMode,
			]),
		);
		m.insert(
			UnitTypeId::Cyclone,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::LockOnLockOn,
			]),
		);
		m.insert(
			UnitTypeId::LocustMPFlying,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::EffectLocustSwoop,
			]),
		);
		m.insert(
			UnitTypeId::Disruptor,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::EffectPurificationNova,
			]),
		);
		m.insert(
			UnitTypeId::VoidMPImmortalReviveCorpse,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
				AbilityId::VoidMPImmortalReviveRebuildImmortal,
			]),
		);
		m.insert(
			UnitTypeId::GuardianMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::DevourerMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::DefilerMPBurrowed,
			HashSet::from([
				AbilityId::DefilerMPUnburrowBurrowUp,
			]),
		);
		m.insert(
			UnitTypeId::DefilerMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::DefilerMPConsumeDefilerMPConsume,
				AbilityId::DefilerMPDarkSwarmDefilerMPDarkSwarm,
				AbilityId::DefilerMPPlagueDefilerMPPlague,
				AbilityId::DefilerMPBurrowBurrowDown,
			]),
		);
		m.insert(
			UnitTypeId::DisruptorPhased,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
			]),
		);
		m.insert(
			UnitTypeId::LiberatorAG,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::AttackAttack,
				AbilityId::MorphLiberatorAAMode,
			]),
		);
		m.insert(
			UnitTypeId::AdeptPhaseShift,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::AttackAttack,
				AbilityId::CancelAdeptShadePhaseShift,
			]),
		);
		m.insert(
			UnitTypeId::HERCPlacement,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::HERC,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::Replicant,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::CorsairMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::CorsairMPDisruptionWebCorsairMPDisruptionWeb,
			]),
		);
		m.insert(
			UnitTypeId::ScoutMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::ArbiterMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::ArbiterMPStasisFieldArbiterMPStasisField,
				AbilityId::ArbiterMPRecallArbiterMPRecall,
			]),
		);
		m.insert(
			UnitTypeId::ScourgeMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::QueenMP,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::AttackAttack,
				AbilityId::QueenMPEnsnareQueenMPEnsnare,
				AbilityId::QueenMPSpawnBroodlingsQueenMPSpawnBroodlings,
				AbilityId::QueenMPInfestCommandCenterQueenMPInfestCommandCenter,
			]),
		);
		m.insert(
			UnitTypeId::ElsecaroColonistHut,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::RallyBuilding,
			]),
		);
		m.insert(
			UnitTypeId::OverlordTransport,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::PatrolPatrol,
				AbilityId::HoldPositionHold,
				AbilityId::ScanMove,
				AbilityId::LoadOverlord,
				AbilityId::MorphOverseer,
				AbilityId::BehaviorGenerateCreepOn,
			]),
		);
		m.insert(
			UnitTypeId::BypassArmorDrone,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::MoveMove,
				AbilityId::AttackAttack,
			]),
		);
		m.insert(
			UnitTypeId::ShieldBattery,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::LoadOutSprayLoadOutSpray1,
			]),
		);
		m.insert(
			UnitTypeId::ObserverSiegeMode,
			HashSet::from([
				AbilityId::StopStop,
				AbilityId::MorphObserverMode,
			]),
		);
		m.insert(
			UnitTypeId::OverseerSiegeMode,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::SpawnChangelingSpawnChangeling,
				AbilityId::ContaminateContaminate,
				AbilityId::MorphOverseerMode,
			]),
		);
		m.insert(
			UnitTypeId::RavenRepairDrone,
			HashSet::from([
				AbilityId::Smart,
				AbilityId::StopStop,
				AbilityId::EffectRepairRepairDrone,
			]),
		);
		m
	};
}